#include "cloak/server_auth.h"
#include "cloak/crypto.h"
#include "test_framework.h"

#include <string.h>
#include <stdio.h>

static size_t hex_decode(const char *hex, uint8_t *out) {
    size_t n = 0;
    size_t hlen = strlen(hex);
    for (size_t i = 0; i + 1 < hlen; i += 2) {
        unsigned int b;
        sscanf(hex + i, "%2x", &b);
        out[n++] = (uint8_t)b;
    }
    return n;
}

/* All vectors below were generated by a Go program using real X25519/AES-256-GCM
 * (golang.org/x/crypto/curve25519, crypto/aes, cipher.NewGCM) and cross-verified
 * against this project's own cloak_x25519_shared_secret/cloak_aead_open/
 * cloak_aead_seal before being written here -- see the plan's Provenance section. */
static const char *SERVER_PRIV_HEX = "25857d6ad7bc967ecb51af16ec15b935bfe3770993acbffe22827bfb6c16bbbd";
static const char *CLIENT_PUB_RANDOM_HEX = "30f47e7ebd1e40e0f69cb739489db3537567983d112c815d6c0a270cec5a7071";
static const char *EXPECTED_SHARED_SECRET_HEX = "6c88df40f5ca673aa30d56850ca3b4f9de2fc7c89de5eb1d2f7cf17fcad43512";
static const char *SESSION_ID_FIELD_HEX = "1d7d86d906f9826efa3c430158e7f824a5044be1f6e76133fe87b2ba98587fef";
static const char *KEY_SHARE_FIELD_HEX = "56e3210d8f44e4a2926bb7d8c3df40eb003b017b075fd6a752e7bb57fb40e9a9";

static const char *SESSION_KEY_HEX = "c0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedf";
static const char *REPLY_NONCE_HEX = "0102030405060708090a0b0c";
static const char *CLIENT_ECHOED_SESSION_ID_HEX = "0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c";
static const char *PAD4_HEX = "2d2e2f30";
static const char *CERT_HEX = "3132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f5051525354";
static const char *EXPECTED_REPLY_HEX =
    "160303007a0200007603030102030405060708090a0b0cd8d8c60aba318b6015f1799a4c6bcad999fc3d84200d0e0f10111213141516171819"
    "1a1b1c1d1e1f202122232425262728292a2b2c130200002e00330024001d002028cdcb21df410ea8d8abefb79f8fc1338f56ba0072696a8ce8"
    "8cf5272d2e2f30002b0002030414030300010117030300243132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505"
    "1525354";

static uint8_t g_server_priv[32];
static uint8_t g_client_pub_random[32];
static uint8_t g_session_id_field[32];
static uint8_t g_key_share_field[32];
static uint8_t g_expected_shared_secret[32];

static void load_shared_vectors(void) {
    hex_decode(SERVER_PRIV_HEX, g_server_priv);
    hex_decode(CLIENT_PUB_RANDOM_HEX, g_client_pub_random);
    hex_decode(SESSION_ID_FIELD_HEX, g_session_id_field);
    hex_decode(KEY_SHARE_FIELD_HEX, g_key_share_field);
    hex_decode(EXPECTED_SHARED_SECRET_HEX, g_expected_shared_secret);
}

/* Embedded timestamp in this vector's plaintext is exactly 1799999999
 * (verified during vector generation); NOW_EXACT has delta 0. */
#define NOW_EXACT 1799999999LL

static void test_decrypt_matches_real_go_vector(void) {
    load_shared_vectors();
    cloak_server_clientinfo_t info;
    uint8_t shared_secret[32];
    int rc = cloak_server_auth_decrypt(g_client_pub_random, g_session_id_field, g_key_share_field,
                                        g_server_priv, NOW_EXACT, &info, shared_secret);
    ASSERT_EQ_INT(rc, 0);
    ASSERT_MEM_EQ(shared_secret, g_expected_shared_secret, 32);

    uint8_t expected_uid[16];
    hex_decode("a0a1a2a3a4a5a6a7a8a9aaabacadaeaf", expected_uid);
    ASSERT_MEM_EQ(info.uid, expected_uid, 16);
    ASSERT_TRUE(strcmp(info.proxy_method, "shadowsocks") == 0);
    ASSERT_EQ_INT(info.encryption_method, 1);
    ASSERT_EQ_INT(info.session_id, 0x12345678);
    ASSERT_TRUE(info.unordered);
}

static void test_timestamp_window_is_strict(void) {
    load_shared_vectors();
    cloak_server_clientinfo_t info;
    uint8_t shared_secret[32];

    ASSERT_EQ_INT(cloak_server_auth_decrypt(g_client_pub_random, g_session_id_field, g_key_share_field,
                                             g_server_priv, NOW_EXACT - 179, &info, shared_secret), 0);
    ASSERT_EQ_INT(cloak_server_auth_decrypt(g_client_pub_random, g_session_id_field, g_key_share_field,
                                             g_server_priv, NOW_EXACT - 180, &info, shared_secret), -1);
    ASSERT_EQ_INT(cloak_server_auth_decrypt(g_client_pub_random, g_session_id_field, g_key_share_field,
                                             g_server_priv, NOW_EXACT + 179, &info, shared_secret), 0);
    ASSERT_EQ_INT(cloak_server_auth_decrypt(g_client_pub_random, g_session_id_field, g_key_share_field,
                                             g_server_priv, NOW_EXACT + 180, &info, shared_secret), -1);
}

static void test_tampered_key_share_rejected(void) {
    load_shared_vectors();
    uint8_t tampered[32];
    memcpy(tampered, g_key_share_field, 32);
    tampered[0] ^= 0xff;

    cloak_server_clientinfo_t info;
    uint8_t shared_secret[32];
    int rc = cloak_server_auth_decrypt(g_client_pub_random, g_session_id_field, tampered,
                                        g_server_priv, NOW_EXACT, &info, shared_secret);
    ASSERT_EQ_INT(rc, -1);
}

static void test_tampered_session_id_rejected(void) {
    load_shared_vectors();
    uint8_t tampered[32];
    memcpy(tampered, g_session_id_field, 32);
    tampered[31] ^= 0x01;

    cloak_server_clientinfo_t info;
    uint8_t shared_secret[32];
    int rc = cloak_server_auth_decrypt(g_client_pub_random, tampered, g_key_share_field,
                                        g_server_priv, NOW_EXACT, &info, shared_secret);
    ASSERT_EQ_INT(rc, -1);
}

static void test_wrong_server_key_rejected(void) {
    load_shared_vectors();
    uint8_t wrong_priv[32];
    memset(wrong_priv, 0x42, 32);

    cloak_server_clientinfo_t info;
    uint8_t shared_secret[32];
    int rc = cloak_server_auth_decrypt(g_client_pub_random, g_session_id_field, g_key_share_field,
                                        wrong_priv, NOW_EXACT, &info, shared_secret);
    ASSERT_EQ_INT(rc, -1);
}

static void test_compose_reply_matches_real_go_vector(void) {
    uint8_t session_key[32], reply_nonce[12], client_session_id[32], pad4[4], cert[36];
    hex_decode(SESSION_KEY_HEX, session_key);
    hex_decode(REPLY_NONCE_HEX, reply_nonce);
    hex_decode(CLIENT_ECHOED_SESSION_ID_HEX, client_session_id);
    hex_decode(PAD4_HEX, pad4);
    hex_decode(CERT_HEX, cert);

    uint8_t expected_reply[256];
    size_t expected_len = hex_decode(EXPECTED_REPLY_HEX, expected_reply);
    ASSERT_EQ_INT(expected_len, 174);

    load_shared_vectors(); /* for g_expected_shared_secret */
    uint8_t out[CLOAK_SERVER_AUTH_REPLY_MAX_BYTES];
    long n = cloak_server_auth_compose_reply(g_expected_shared_secret, session_key, reply_nonce,
                                              client_session_id, pad4, cert, sizeof(cert), out, sizeof(out));
    ASSERT_EQ_INT(n, 174);
    ASSERT_MEM_EQ(out, expected_reply, 174);
}

static void test_compose_reply_rejects_invalid_cert_len(void) {
    load_shared_vectors();
    uint8_t session_key[32] = {0};
    uint8_t reply_nonce[12] = {0};
    uint8_t client_session_id[32] = {0};
    uint8_t pad4[4] = {0};
    uint8_t cert[10] = {0}; /* 10 is not in cloak_server_auth_cert_lens */

    uint8_t out[CLOAK_SERVER_AUTH_REPLY_MAX_BYTES];
    long n = cloak_server_auth_compose_reply(g_expected_shared_secret, session_key, reply_nonce,
                                              client_session_id, pad4, cert, sizeof(cert), out, sizeof(out));
    ASSERT_EQ_INT(n, -1);
}

static void test_compose_reply_rejects_undersized_buffer(void) {
    load_shared_vectors();
    uint8_t session_key[32] = {0};
    uint8_t reply_nonce[12] = {0};
    uint8_t client_session_id[32] = {0};
    uint8_t pad4[4] = {0};
    uint8_t cert[27] = {0}; /* valid length */

    uint8_t out[10]; /* too small for any valid reply (min total is 5+122+5+1+5+27=165) */
    long n = cloak_server_auth_compose_reply(g_expected_shared_secret, session_key, reply_nonce,
                                              client_session_id, pad4, cert, sizeof(cert), out, sizeof(out));
    ASSERT_EQ_INT(n, -1);
}

static void test_compose_reply_all_cert_lens_succeed(void) {
    load_shared_vectors();
    uint8_t session_key[32] = {0};
    uint8_t reply_nonce[12] = {0};
    uint8_t client_session_id[32] = {0};
    uint8_t pad4[4] = {0};
    uint8_t cert[68] = {0}; /* max cert len */

    for (size_t i = 0; i < CLOAK_SERVER_AUTH_CERT_LEN_COUNT; i++) {
        size_t cert_len = cloak_server_auth_cert_lens[i];
        uint8_t out[CLOAK_SERVER_AUTH_REPLY_MAX_BYTES];
        long n = cloak_server_auth_compose_reply(g_expected_shared_secret, session_key, reply_nonce,
                                                  client_session_id, pad4, cert, cert_len, out, sizeof(out));
        ASSERT_TRUE(n > 0);
        ASSERT_EQ_INT((size_t)n, 5 + 122 + 5 + 1 + 5 + cert_len);
        ASSERT_TRUE((size_t)n <= CLOAK_SERVER_AUTH_REPLY_MAX_BYTES);
    }
}

static void test_timestamp_extreme_now_unix_no_ub(void) {
    load_shared_vectors();
    cloak_server_clientinfo_t info;
    uint8_t shared_secret[32];

    /* now_unix near INT64_MIN/INT64_MAX must not crash or hang -- both must
     * cleanly reject (the fixed vector's timestamp, 1799999999, is nowhere
     * near either extreme, so both should be well outside the window). */
    int rc_min = cloak_server_auth_decrypt(g_client_pub_random, g_session_id_field, g_key_share_field,
                                            g_server_priv, INT64_MIN, &info, shared_secret);
    ASSERT_EQ_INT(rc_min, -1);
    int rc_max = cloak_server_auth_decrypt(g_client_pub_random, g_session_id_field, g_key_share_field,
                                            g_server_priv, INT64_MAX, &info, shared_secret);
    ASSERT_EQ_INT(rc_max, -1);
}

TEST_MAIN_BEGIN()
    test_decrypt_matches_real_go_vector();
    test_timestamp_window_is_strict();
    test_tampered_key_share_rejected();
    test_tampered_session_id_rejected();
    test_wrong_server_key_rejected();
    test_compose_reply_matches_real_go_vector();
    test_compose_reply_rejects_invalid_cert_len();
    test_compose_reply_rejects_undersized_buffer();
    test_compose_reply_all_cert_lens_succeed();
    test_timestamp_extreme_now_unix_no_ub();
TEST_MAIN_END()
